### PR TITLE
Update 5 NuGet dependencies

### PR DESCRIPTION
**Pull request by nfbot**
Bumps nanoFramework.CoreLibrary from 1.10.5 to 1.11.6-preview.2</br>Bumps nanoFramework.Runtime.Events from 1.9.2-preview.5 to 1.9.2-preview.8</br>Bumps nanoFramework.System.IO.Ports from 1.0.1-preview.13 to 1.0.1-preview.21</br>Bumps nanoFramework.System.IO.FileSystem from 1.0.2-preview.10 to 1.0.2-preview.12</br>Bumps nanoFramework.Hardware.Esp32 from 1.3.4-preview.5 to 1.3.4-preview.11</br>
[version update]

### CODE REVIEW

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Review by networkfusion — APPROVED** [review]

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Review by networkfusion — APPROVED** [review]

**Comment by josesimoes** [comment]
@nfbot updatedependents

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Pull request closed without merging**
