### PR TITLE
Adding custom formatting for logs

### PR DESCRIPTION
**Pull request by Ellerbach**
## Description

Adding custom formatting for logs

## Motivation and Context

- Add the possibility to customize the way the logs are formed
- Fixed issue with stream to stay open

## How Has This Been Tested?

With the unit tests

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by josesimoes** [comment]
@Ellerbach care to look at Sonarcloud issues? 😉

**Comment by Ellerbach** [comment]
> @Ellerbach care to look at Sonarcloud issues? 😉

it's clean for the smells ;-)
image

It doesn't like the duplication of code between Serial and Stream. I just don't want to over complicate it. 
image

**Comment by Ellerbach** [comment]
> @Ellerbach care to look at Sonarcloud issues? 😉

it's clean for the smells ;-)
image

It doesn't like the duplication of code between Serial and Stream. I just don't want to over complicate it. 
image

**Review by josesimoes — APPROVED** [review]
LGTM!

**Pull request merged**
